version: "3.8"
services:
    mongodb:
        image: "mongo"
        volumes:
            - data:/data/db
        ports:
            - "27017:27017"
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        env_file:
            - ./env/backend.env
        depends_on:
            - mongodb

volumes:
    data: